export const GET_CATEGORIES = {
  SUCCESS: "GET_CATEGORIES_SUCCESS",
  ERROR: "GET_CATEGORIES_ERROR",
  PANDING: "GET_CATEGORIES_PANDING"
};

export const GET_CAT_PHOTOS_BY_CATEGORY_ID = {
  SUCCESS: "GET_CAT_PHOTOS_BY_CATEGORY_ID_SUCCESS",
  ERROR: "GET_CAT_PHOTOS_BY_CATEGORY_ID_ERROR",
  PANDING: "GET_CAT_PHOTOS_BY_CATEGORY_ID_PANDING"
};

export const GET_MORE_IN_CURRENT_CATEGORY_SUCCESS =
  "GET_MORE_IN_CURRENT_CATEGORY_SUCCESS";

export const SELECT_CURRENT_CATEGORY = "SELECT_CURRENT_CATEGORY";
